### ISSUE TITLE
Possibly allow tastypie to interface with waterline rather than mongoose

### ISSUE THREAD

**Issue by devinivy** [node-tastypie/tastypie#2]
Perhaps interfacing with an adapter-based ORM would be nice, so that non-mongodb using users could take advantage of tastypie.  I would suggest checking-out [waterline](https://github.com/balderdashy/waterline), whose built-in types closely mirror tastypie's.

**Comment by esatterwhite** [comment]
Tastypie isn't locked to mongoose, it is just one of the resource types I implemented. The base resource doesn't assume any data source, it is just a matter of subclassing & implementing. Which you could do in your project. 

Also, my working knowledge of waterline is limited. I would openly welcome a PR, or even a branch/fork with some ground work.

**Comment by devinivy** [comment]
Cool– may give it a whirl if I find some free time.  I figure it may be an easy way to have someone else deal with implementing resources– there's a whole community around it in the waterline ecosystem.  You're welcome to close this if you'd like!

**Comment by esatterwhite** [comment]
I don't think it would too difficult. That was the idea in the first place. I think much of it would pivot on if you can pre-define a query & criteria like mquery allows with `toConstructor` to maintain api parody with the way the mongoose resource works.

It looks like there is a Query class in waterline, so it is probable.

Will leave this open for a point of reference

**Comment by esatterwhite** [comment]
@devinivy if this is still of interest with you, you could check out on of the sub projects [tastypie-mongo](https://github.com/node-tastypie/tastypie-mongo) or [tastypie-rethink](https://github.com/node-tastypie/tastypie-rethink)

it isn't terribly difficult. The bulk of the work comes down to implementing [filters](https://github.com/node-tastypie/tastypie-rethink/tree/master/lib/resource/filters). Even that isn't difficult, once you have one done, they are all pretty similar.

**Comment by devinivy** [comment]
Excellent, thanks!  I think we can close this out!
